language: node_js
node_js:
  - "10"
before_install:
  - npm install -g @angular/cli
install: npm install
branches:
  only:
    - main
deploy:
  provider: heroku
  app: angular-clicker-hw3,
  api_key:
    secure: W5vNpcQLsuK/5sxEM6FvyrXx9BLjVL5y1Q88/1tFFDpo3d/y00mTY+yzgyNaPxYK26j0T36hFd2jQbGNYhlNHi6cldtTaBiWdmFWVMFaIccNtmza56Gru2qTL6C29BOJCGkLAJHYaexoS3wTnbC9CcIXsxJplb4FoxIL5UAt2C0yOedVDNvyzPLEV3VB6ry/X4x9EiWppwYWufA0IQZ5ZS2DZ1aqH1GQ2oB8fcIMHvLvrbKk9qPP/ZrZwcIC5hFnTaxoZkyu+PKHYHFmno6TVdjvXXg6IQdSWEWK8EaN++SX+u3H+CeOzeUXYB1nGZjwgnTvhy0UHAKK9Bt+9l0ZPFgRTa0BfWnyhMF771HWdK9EQZGTgop6ZrRnkfDJ2iKvnhxQ5IzziJI3YixwBKTNfg6WO9F0ljX4Q7QxdGNlt5MxU6lWWQFD7EJAsXG81ZCCYmn8se3aI0BxEswhwgaRimf/hd4C1+/ScuyO0zuJ1nhxrcpdb63DW5b6FcJPBkBA8o9duc1DVhgYwUUMDor6kp5fzyV7DDcPX2Y3VVv2vCE9DuW2Tk83NZx0GIMzOJRtgUd3Rs7lZjFwANpIDkPC2qYeCnSbuwjafVxTrWPmzb/N9XNQOrx++Aip0kKSi84fJsIaqNoXxDpKZ6CuZRJ70H2CNxfaMsffjcASbJB4hh4=
