language: node_js
node_js:
  - "10"
before_install:
  - npm install -g @angular/cli
install: npm install
deploy:
  provider: heroku
  app: angular-clicker-hw3,
  api_key:
    secure: WTmRaEvH5zDE6MKWjw1EKuwbngawNQWqC5VCoOcfvD9AxDL/1pYrQwqM9ke8/Fbkau23seQU56Y3nNVlRHK3CbQA9wxVvquDHlef2AcE4zW3uquUoPdFx0cYkX7/cfLsGz8tuztSnEpjDUNNw6Cq/ULfOgBoQ2yRZpqhFoM94Sgn+4ejind95JOjiq+JQ9aJlxxUdJbs0ZUlPM+J8SxAbK4qDo9uqg84K3yyS2p4Y4tx+iYNurGkUF0NKGptX0Bpl56CbOMYfgMxK85lKX0FPPCG2oL8xEd6IkPQ0LIS9R+hszznWOgbvsrEW4tE7/6HbCvq3LQliebddFJD/HM7qtfWEs18bkUnFDe2ZiPupLDt0zk66NazIaFzLFLzLGm3N+L7xi581U/msLwEFFdf/un6/uAawxburrmj9Fa0Nk3ZWpq24DPd6005xcwmzidLJBTdmD14tHXMx4GMy5M6wnwkaoy4s318jj9AeA+JFGk/nEtqtLdTeaPE4l1OD0HBWFfrQQDjYQSDL7vlCBqMcGAUYg+o/u69la8vQHVgQwp3Lt5Yogo7oI0oFFT8Vd6wLrzkKcUuUkP8WIiHBAJz9W7jG4r4zqHKEQfXK5soGEnb3z8zh7IEJu6oPMotiWTPyRZWmUmFWjFhSWirjR1DpWbULmucZ8gW5s2zyRvuB9U=
  on: main
